#############################################################################
# Makefile for building: .build/bin/jim
# Generated by qmake (3.1) (Qt 6.9.2)
# Project:  jim.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile jim.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT $(DEFINES)
INCPATH       = -I. -Iinclude -Iinclude/app -Iinclude/editor -Iinclude/ai -Iinclude/audio -Iinclude/tools/binary -Iinclude/tools/preview -Iinclude/tools/visualization -Iinclude/analysis -Iinclude/story -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I.build/moc -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = jim1.0.0
DISTDIR = /mnt/d/fun\ stuff/jim/.build/obj/jim1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt6Widgets.so /usr/lib/x86_64-linux-gnu/libQt6Multimedia.so /usr/lib/x86_64-linux-gnu/libQt6Gui.so /usr/lib/x86_64-linux-gnu/libGLX.so /usr/lib/x86_64-linux-gnu/libOpenGL.so /usr/lib/x86_64-linux-gnu/libQt6Network.so /usr/lib/x86_64-linux-gnu/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = .build/obj/

####### Files

SOURCES       = src/app/main.cpp \
		src/app/breadcrumb_bar.cpp \
		src/app/command_palette.cpp \
		src/app/draggable_tabs.cpp \
		src/app/find_bar.cpp \
		src/app/search_everywhere.cpp \
		src/app/terminal_widget.cpp \
		src/app/texteditor.cpp \
		src/app/texteditor_actions.cpp \
		src/app/texteditor_documents.cpp \
		src/app/texteditor_features.cpp \
		src/app/texteditor_panels.cpp \
		src/app/texteditor_tools.cpp \
		src/app/title_bar.cpp \
		src/app/todo_panel.cpp \
		src/app/welcome_widget.cpp \
		src/editor/animationwidget.cpp \
		src/editor/codeeditor.cpp \
		src/editor/keyheatmap.cpp \
		src/editor/linenumberarea.cpp \
		src/editor/overlays.cpp \
		src/editor/syntaxhighlighter.cpp \
		src/editor/vimmode.cpp \
		src/ai/aiautocomplete.cpp \
		src/ai/aisettingsdialog.cpp \
		src/audio/audiomonitor.cpp \
		src/tools/binary/binaryinspector.cpp \
		src/tools/binary/disassembler.cpp \
		src/tools/binary/hexeditor.cpp \
		src/tools/preview/markdownviewer.cpp \
		src/tools/visualization/cityscape_widget.cpp \
		src/tools/visualization/codegraph.cpp \
		src/analysis/solidityanalyzer.cpp \
		src/analysis/storageslotvisualizer.cpp \
		src/analysis/vulnscanner.cpp \
		src/story/storyexporter.cpp \
		src/story/storygraph.cpp \
		src/story/storyparser.cpp \
		src/story/storyplaytest.cpp .build/moc/moc_texteditor.cpp \
		.build/moc/moc_breadcrumb_bar.cpp \
		.build/moc/moc_command_palette.cpp \
		.build/moc/moc_draggable_tabs.cpp \
		.build/moc/moc_find_bar.cpp \
		.build/moc/moc_search_everywhere.cpp \
		.build/moc/moc_terminal_widget.cpp \
		.build/moc/moc_todo_panel.cpp \
		.build/moc/moc_title_bar.cpp \
		.build/moc/moc_welcome_widget.cpp \
		.build/moc/moc_animationwidget.cpp \
		.build/moc/moc_codeeditor.cpp \
		.build/moc/moc_folding_area.cpp \
		.build/moc/moc_minimap.cpp \
		.build/moc/moc_overlays.cpp \
		.build/moc/moc_keyheatmap.cpp \
		.build/moc/moc_syntaxhighlighter.cpp \
		.build/moc/moc_vimmode.cpp \
		.build/moc/moc_aiautocomplete.cpp \
		.build/moc/moc_aisettingsdialog.cpp \
		.build/moc/moc_audiomonitor.cpp \
		.build/moc/moc_binaryinspector.cpp \
		.build/moc/moc_disassembler.cpp \
		.build/moc/moc_hexeditor.cpp \
		.build/moc/moc_markdownviewer.cpp \
		.build/moc/moc_cityscape_widget.cpp \
		.build/moc/moc_codegraph.cpp \
		.build/moc/moc_storageslotvisualizer.cpp \
		.build/moc/moc_vulnscanner.cpp \
		.build/moc/moc_storygraph.cpp \
		.build/moc/moc_storyplaytest.cpp
OBJECTS       = .build/obj/main.o \
		.build/obj/breadcrumb_bar.o \
		.build/obj/command_palette.o \
		.build/obj/draggable_tabs.o \
		.build/obj/find_bar.o \
		.build/obj/search_everywhere.o \
		.build/obj/terminal_widget.o \
		.build/obj/texteditor.o \
		.build/obj/texteditor_actions.o \
		.build/obj/texteditor_documents.o \
		.build/obj/texteditor_features.o \
		.build/obj/texteditor_panels.o \
		.build/obj/texteditor_tools.o \
		.build/obj/title_bar.o \
		.build/obj/todo_panel.o \
		.build/obj/welcome_widget.o \
		.build/obj/animationwidget.o \
		.build/obj/codeeditor.o \
		.build/obj/keyheatmap.o \
		.build/obj/linenumberarea.o \
		.build/obj/overlays.o \
		.build/obj/syntaxhighlighter.o \
		.build/obj/vimmode.o \
		.build/obj/aiautocomplete.o \
		.build/obj/aisettingsdialog.o \
		.build/obj/audiomonitor.o \
		.build/obj/binaryinspector.o \
		.build/obj/disassembler.o \
		.build/obj/hexeditor.o \
		.build/obj/markdownviewer.o \
		.build/obj/cityscape_widget.o \
		.build/obj/codegraph.o \
		.build/obj/solidityanalyzer.o \
		.build/obj/storageslotvisualizer.o \
		.build/obj/vulnscanner.o \
		.build/obj/storyexporter.o \
		.build/obj/storygraph.o \
		.build/obj/storyparser.o \
		.build/obj/storyplaytest.o \
		.build/obj/moc_texteditor.o \
		.build/obj/moc_breadcrumb_bar.o \
		.build/obj/moc_command_palette.o \
		.build/obj/moc_draggable_tabs.o \
		.build/obj/moc_find_bar.o \
		.build/obj/moc_search_everywhere.o \
		.build/obj/moc_terminal_widget.o \
		.build/obj/moc_todo_panel.o \
		.build/obj/moc_title_bar.o \
		.build/obj/moc_welcome_widget.o \
		.build/obj/moc_animationwidget.o \
		.build/obj/moc_codeeditor.o \
		.build/obj/moc_folding_area.o \
		.build/obj/moc_minimap.o \
		.build/obj/moc_overlays.o \
		.build/obj/moc_keyheatmap.o \
		.build/obj/moc_syntaxhighlighter.o \
		.build/obj/moc_vimmode.o \
		.build/obj/moc_aiautocomplete.o \
		.build/obj/moc_aisettingsdialog.o \
		.build/obj/moc_audiomonitor.o \
		.build/obj/moc_binaryinspector.o \
		.build/obj/moc_disassembler.o \
		.build/obj/moc_hexeditor.o \
		.build/obj/moc_markdownviewer.o \
		.build/obj/moc_cityscape_widget.o \
		.build/obj/moc_codegraph.o \
		.build/obj/moc_storageslotvisualizer.o \
		.build/obj/moc_vulnscanner.o \
		.build/obj/moc_storygraph.o \
		.build/obj/moc_storyplaytest.o
DIST          = /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/permissions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		jim.pro include/app/texteditor.h \
		include/app/breadcrumb_bar.h \
		include/app/command_palette.h \
		include/app/draggable_tabs.h \
		include/app/find_bar.h \
		include/app/search_everywhere.h \
		include/app/terminal_widget.h \
		include/app/todo_panel.h \
		include/app/title_bar.h \
		include/app/welcome_widget.h \
		include/editor/animationwidget.h \
		include/editor/codeeditor.h \
		include/editor/folding_area.h \
		include/editor/line_number_area.h \
		include/editor/minimap.h \
		include/editor/overlays.h \
		include/editor/keyheatmap.h \
		include/editor/syntaxhighlighter.h \
		include/editor/vimmode.h \
		include/ai/aiautocomplete.h \
		include/ai/aisettingsdialog.h \
		include/audio/audiomonitor.h \
		include/tools/binary/binaryinspector.h \
		include/tools/binary/disassembler.h \
		include/tools/binary/hexeditor.h \
		include/tools/preview/markdownviewer.h \
		include/tools/visualization/cityscape_widget.h \
		include/tools/visualization/codegraph.h \
		include/analysis/solidityanalyzer.h \
		include/analysis/storageslotvisualizer.h \
		include/analysis/vulnscanner.h \
		include/story/storyexporter.h \
		include/story/storygraph.h \
		include/story/storyparser.h \
		include/story/storyplaytest.h src/app/main.cpp \
		src/app/breadcrumb_bar.cpp \
		src/app/command_palette.cpp \
		src/app/draggable_tabs.cpp \
		src/app/find_bar.cpp \
		src/app/search_everywhere.cpp \
		src/app/terminal_widget.cpp \
		src/app/texteditor.cpp \
		src/app/texteditor_actions.cpp \
		src/app/texteditor_documents.cpp \
		src/app/texteditor_features.cpp \
		src/app/texteditor_panels.cpp \
		src/app/texteditor_tools.cpp \
		src/app/title_bar.cpp \
		src/app/todo_panel.cpp \
		src/app/welcome_widget.cpp \
		src/editor/animationwidget.cpp \
		src/editor/codeeditor.cpp \
		src/editor/keyheatmap.cpp \
		src/editor/linenumberarea.cpp \
		src/editor/overlays.cpp \
		src/editor/syntaxhighlighter.cpp \
		src/editor/vimmode.cpp \
		src/ai/aiautocomplete.cpp \
		src/ai/aisettingsdialog.cpp \
		src/audio/audiomonitor.cpp \
		src/tools/binary/binaryinspector.cpp \
		src/tools/binary/disassembler.cpp \
		src/tools/binary/hexeditor.cpp \
		src/tools/preview/markdownviewer.cpp \
		src/tools/visualization/cityscape_widget.cpp \
		src/tools/visualization/codegraph.cpp \
		src/analysis/solidityanalyzer.cpp \
		src/analysis/storageslotvisualizer.cpp \
		src/analysis/vulnscanner.cpp \
		src/story/storyexporter.cpp \
		src/story/storygraph.cpp \
		src/story/storyparser.cpp \
		src/story/storyplaytest.cpp
QMAKE_TARGET  = jim
DESTDIR       = .build/bin/
TARGET        = .build/bin/jim


first: all
####### Build rules

.build/bin/jim:  $(OBJECTS)  
	@test -d .build/bin/ || mkdir -p .build/bin/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: jim.pro /usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/permissions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		jim.pro \
		/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Multimedia.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Core.prl
	$(QMAKE) -o Makefile jim.pro
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_example_icons_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_spatialaudio.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testinternals_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/link_pkgconfig.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/permissions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf:
jim.pro:
/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt6Multimedia.prl:
/usr/lib/x86_64-linux-gnu/libQt6Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt6Network.prl:
/usr/lib/x86_64-linux-gnu/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile jim.pro

qmake_all: FORCE


all: Makefile .build/bin/jim

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/app/texteditor.h include/app/breadcrumb_bar.h include/app/command_palette.h include/app/draggable_tabs.h include/app/find_bar.h include/app/search_everywhere.h include/app/terminal_widget.h include/app/todo_panel.h include/app/title_bar.h include/app/welcome_widget.h include/editor/animationwidget.h include/editor/codeeditor.h include/editor/folding_area.h include/editor/line_number_area.h include/editor/minimap.h include/editor/overlays.h include/editor/keyheatmap.h include/editor/syntaxhighlighter.h include/editor/vimmode.h include/ai/aiautocomplete.h include/ai/aisettingsdialog.h include/audio/audiomonitor.h include/tools/binary/binaryinspector.h include/tools/binary/disassembler.h include/tools/binary/hexeditor.h include/tools/preview/markdownviewer.h include/tools/visualization/cityscape_widget.h include/tools/visualization/codegraph.h include/analysis/solidityanalyzer.h include/analysis/storageslotvisualizer.h include/analysis/vulnscanner.h include/story/storyexporter.h include/story/storygraph.h include/story/storyparser.h include/story/storyplaytest.h $(DISTDIR)/
	$(COPY_FILE) --parents src/app/main.cpp src/app/breadcrumb_bar.cpp src/app/command_palette.cpp src/app/draggable_tabs.cpp src/app/find_bar.cpp src/app/search_everywhere.cpp src/app/terminal_widget.cpp src/app/texteditor.cpp src/app/texteditor_actions.cpp src/app/texteditor_documents.cpp src/app/texteditor_features.cpp src/app/texteditor_panels.cpp src/app/texteditor_tools.cpp src/app/title_bar.cpp src/app/todo_panel.cpp src/app/welcome_widget.cpp src/editor/animationwidget.cpp src/editor/codeeditor.cpp src/editor/keyheatmap.cpp src/editor/linenumberarea.cpp src/editor/overlays.cpp src/editor/syntaxhighlighter.cpp src/editor/vimmode.cpp src/ai/aiautocomplete.cpp src/ai/aisettingsdialog.cpp src/audio/audiomonitor.cpp src/tools/binary/binaryinspector.cpp src/tools/binary/disassembler.cpp src/tools/binary/hexeditor.cpp src/tools/preview/markdownviewer.cpp src/tools/visualization/cityscape_widget.cpp src/tools/visualization/codegraph.cpp src/analysis/solidityanalyzer.cpp src/analysis/storageslotvisualizer.cpp src/analysis/vulnscanner.cpp src/story/storyexporter.cpp src/story/storygraph.cpp src/story/storyparser.cpp src/story/storyplaytest.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: .build/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) .build/moc/moc_predefs.h
.build/moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o .build/moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: .build/moc/moc_texteditor.cpp .build/moc/moc_breadcrumb_bar.cpp .build/moc/moc_command_palette.cpp .build/moc/moc_draggable_tabs.cpp .build/moc/moc_find_bar.cpp .build/moc/moc_search_everywhere.cpp .build/moc/moc_terminal_widget.cpp .build/moc/moc_todo_panel.cpp .build/moc/moc_title_bar.cpp .build/moc/moc_welcome_widget.cpp .build/moc/moc_animationwidget.cpp .build/moc/moc_codeeditor.cpp .build/moc/moc_folding_area.cpp .build/moc/moc_minimap.cpp .build/moc/moc_overlays.cpp .build/moc/moc_keyheatmap.cpp .build/moc/moc_syntaxhighlighter.cpp .build/moc/moc_vimmode.cpp .build/moc/moc_aiautocomplete.cpp .build/moc/moc_aisettingsdialog.cpp .build/moc/moc_audiomonitor.cpp .build/moc/moc_binaryinspector.cpp .build/moc/moc_disassembler.cpp .build/moc/moc_hexeditor.cpp .build/moc/moc_markdownviewer.cpp .build/moc/moc_cityscape_widget.cpp .build/moc/moc_codegraph.cpp .build/moc/moc_storageslotvisualizer.cpp .build/moc/moc_vulnscanner.cpp .build/moc/moc_storygraph.cpp .build/moc/moc_storyplaytest.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .build/moc/moc_texteditor.cpp .build/moc/moc_breadcrumb_bar.cpp .build/moc/moc_command_palette.cpp .build/moc/moc_draggable_tabs.cpp .build/moc/moc_find_bar.cpp .build/moc/moc_search_everywhere.cpp .build/moc/moc_terminal_widget.cpp .build/moc/moc_todo_panel.cpp .build/moc/moc_title_bar.cpp .build/moc/moc_welcome_widget.cpp .build/moc/moc_animationwidget.cpp .build/moc/moc_codeeditor.cpp .build/moc/moc_folding_area.cpp .build/moc/moc_minimap.cpp .build/moc/moc_overlays.cpp .build/moc/moc_keyheatmap.cpp .build/moc/moc_syntaxhighlighter.cpp .build/moc/moc_vimmode.cpp .build/moc/moc_aiautocomplete.cpp .build/moc/moc_aisettingsdialog.cpp .build/moc/moc_audiomonitor.cpp .build/moc/moc_binaryinspector.cpp .build/moc/moc_disassembler.cpp .build/moc/moc_hexeditor.cpp .build/moc/moc_markdownviewer.cpp .build/moc/moc_cityscape_widget.cpp .build/moc/moc_codegraph.cpp .build/moc/moc_storageslotvisualizer.cpp .build/moc/moc_vulnscanner.cpp .build/moc/moc_storygraph.cpp .build/moc/moc_storyplaytest.cpp
.build/moc/moc_texteditor.cpp: include/app/texteditor.h \
		include/editor/codeeditor.h \
		include/editor/syntaxhighlighter.h \
		include/analysis/vulnscanner.h \
		include/analysis/solidityanalyzer.h \
		include/analysis/storageslotvisualizer.h \
		include/story/storyparser.h \
		include/story/storygraph.h \
		include/story/storyplaytest.h \
		include/story/storyexporter.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/app/texteditor.h -o .build/moc/moc_texteditor.cpp

.build/moc/moc_breadcrumb_bar.cpp: include/app/breadcrumb_bar.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/app/breadcrumb_bar.h -o .build/moc/moc_breadcrumb_bar.cpp

.build/moc/moc_command_palette.cpp: include/app/command_palette.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/app/command_palette.h -o .build/moc/moc_command_palette.cpp

.build/moc/moc_draggable_tabs.cpp: include/app/draggable_tabs.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/app/draggable_tabs.h -o .build/moc/moc_draggable_tabs.cpp

.build/moc/moc_find_bar.cpp: include/app/find_bar.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/app/find_bar.h -o .build/moc/moc_find_bar.cpp

.build/moc/moc_search_everywhere.cpp: include/app/search_everywhere.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/app/search_everywhere.h -o .build/moc/moc_search_everywhere.cpp

.build/moc/moc_terminal_widget.cpp: include/app/terminal_widget.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/app/terminal_widget.h -o .build/moc/moc_terminal_widget.cpp

.build/moc/moc_todo_panel.cpp: include/app/todo_panel.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/app/todo_panel.h -o .build/moc/moc_todo_panel.cpp

.build/moc/moc_title_bar.cpp: include/app/title_bar.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/app/title_bar.h -o .build/moc/moc_title_bar.cpp

.build/moc/moc_welcome_widget.cpp: include/app/welcome_widget.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/app/welcome_widget.h -o .build/moc/moc_welcome_widget.cpp

.build/moc/moc_animationwidget.cpp: include/editor/animationwidget.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/editor/animationwidget.h -o .build/moc/moc_animationwidget.cpp

.build/moc/moc_codeeditor.cpp: include/editor/codeeditor.h \
		include/editor/syntaxhighlighter.h \
		include/analysis/vulnscanner.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/editor/codeeditor.h -o .build/moc/moc_codeeditor.cpp

.build/moc/moc_folding_area.cpp: include/editor/folding_area.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/editor/folding_area.h -o .build/moc/moc_folding_area.cpp

.build/moc/moc_minimap.cpp: include/editor/minimap.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/editor/minimap.h -o .build/moc/moc_minimap.cpp

.build/moc/moc_overlays.cpp: include/editor/overlays.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/editor/overlays.h -o .build/moc/moc_overlays.cpp

.build/moc/moc_keyheatmap.cpp: include/editor/keyheatmap.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/editor/keyheatmap.h -o .build/moc/moc_keyheatmap.cpp

.build/moc/moc_syntaxhighlighter.cpp: include/editor/syntaxhighlighter.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/editor/syntaxhighlighter.h -o .build/moc/moc_syntaxhighlighter.cpp

.build/moc/moc_vimmode.cpp: include/editor/vimmode.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/editor/vimmode.h -o .build/moc/moc_vimmode.cpp

.build/moc/moc_aiautocomplete.cpp: include/ai/aiautocomplete.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/ai/aiautocomplete.h -o .build/moc/moc_aiautocomplete.cpp

.build/moc/moc_aisettingsdialog.cpp: include/ai/aisettingsdialog.h \
		include/ai/aiautocomplete.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/ai/aisettingsdialog.h -o .build/moc/moc_aisettingsdialog.cpp

.build/moc/moc_audiomonitor.cpp: include/audio/audiomonitor.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/audio/audiomonitor.h -o .build/moc/moc_audiomonitor.cpp

.build/moc/moc_binaryinspector.cpp: include/tools/binary/binaryinspector.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/tools/binary/binaryinspector.h -o .build/moc/moc_binaryinspector.cpp

.build/moc/moc_disassembler.cpp: include/tools/binary/disassembler.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/tools/binary/disassembler.h -o .build/moc/moc_disassembler.cpp

.build/moc/moc_hexeditor.cpp: include/tools/binary/hexeditor.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/tools/binary/hexeditor.h -o .build/moc/moc_hexeditor.cpp

.build/moc/moc_markdownviewer.cpp: include/tools/preview/markdownviewer.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/tools/preview/markdownviewer.h -o .build/moc/moc_markdownviewer.cpp

.build/moc/moc_cityscape_widget.cpp: include/tools/visualization/cityscape_widget.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/tools/visualization/cityscape_widget.h -o .build/moc/moc_cityscape_widget.cpp

.build/moc/moc_codegraph.cpp: include/tools/visualization/codegraph.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/tools/visualization/codegraph.h -o .build/moc/moc_codegraph.cpp

.build/moc/moc_storageslotvisualizer.cpp: include/analysis/storageslotvisualizer.h \
		include/analysis/solidityanalyzer.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/analysis/storageslotvisualizer.h -o .build/moc/moc_storageslotvisualizer.cpp

.build/moc/moc_vulnscanner.cpp: include/analysis/vulnscanner.h \
		include/editor/syntaxhighlighter.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/analysis/vulnscanner.h -o .build/moc/moc_vulnscanner.cpp

.build/moc/moc_storygraph.cpp: include/story/storygraph.h \
		include/story/storyparser.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/story/storygraph.h -o .build/moc/moc_storygraph.cpp

.build/moc/moc_storyplaytest.cpp: include/story/storyplaytest.h \
		include/story/storyparser.h \
		.build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include '/mnt/d/fun stuff/jim/.build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I'/mnt/d/fun stuff/jim' -I'/mnt/d/fun stuff/jim/include' -I'/mnt/d/fun stuff/jim/include/app' -I'/mnt/d/fun stuff/jim/include/editor' -I'/mnt/d/fun stuff/jim/include/ai' -I'/mnt/d/fun stuff/jim/include/audio' -I'/mnt/d/fun stuff/jim/include/tools/binary' -I'/mnt/d/fun stuff/jim/include/tools/preview' -I'/mnt/d/fun stuff/jim/include/tools/visualization' -I'/mnt/d/fun stuff/jim/include/analysis' -I'/mnt/d/fun stuff/jim/include/story' -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/story/storyplaytest.h -o .build/moc/moc_storyplaytest.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

.build/obj/main.o: src/app/main.cpp include/app/texteditor.h \
		include/editor/codeeditor.h \
		include/editor/syntaxhighlighter.h \
		include/analysis/vulnscanner.h \
		include/analysis/solidityanalyzer.h \
		include/analysis/storageslotvisualizer.h \
		include/story/storyparser.h \
		include/story/storygraph.h \
		include/story/storyplaytest.h \
		include/story/storyexporter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/main.o src/app/main.cpp

.build/obj/breadcrumb_bar.o: src/app/breadcrumb_bar.cpp include/app/breadcrumb_bar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/breadcrumb_bar.o src/app/breadcrumb_bar.cpp

.build/obj/command_palette.o: src/app/command_palette.cpp include/app/command_palette.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/command_palette.o src/app/command_palette.cpp

.build/obj/draggable_tabs.o: src/app/draggable_tabs.cpp include/app/draggable_tabs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/draggable_tabs.o src/app/draggable_tabs.cpp

.build/obj/find_bar.o: src/app/find_bar.cpp include/app/find_bar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/find_bar.o src/app/find_bar.cpp

.build/obj/search_everywhere.o: src/app/search_everywhere.cpp include/app/search_everywhere.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/search_everywhere.o src/app/search_everywhere.cpp

.build/obj/terminal_widget.o: src/app/terminal_widget.cpp include/app/terminal_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/terminal_widget.o src/app/terminal_widget.cpp

.build/obj/texteditor.o: src/app/texteditor.cpp src/app/texteditor_private.h \
		include/app/texteditor.h \
		include/editor/codeeditor.h \
		include/editor/syntaxhighlighter.h \
		include/analysis/vulnscanner.h \
		include/analysis/solidityanalyzer.h \
		include/analysis/storageslotvisualizer.h \
		include/story/storyparser.h \
		include/story/storygraph.h \
		include/story/storyplaytest.h \
		include/story/storyexporter.h \
		include/app/breadcrumb_bar.h \
		include/app/command_palette.h \
		include/app/draggable_tabs.h \
		include/app/find_bar.h \
		include/app/search_everywhere.h \
		include/app/terminal_widget.h \
		include/app/todo_panel.h \
		include/app/title_bar.h \
		include/app/welcome_widget.h \
		include/editor/animationwidget.h \
		include/editor/overlays.h \
		include/editor/keyheatmap.h \
		include/editor/vimmode.h \
		include/tools/binary/hexeditor.h \
		include/tools/binary/disassembler.h \
		include/tools/binary/binaryinspector.h \
		include/tools/preview/markdownviewer.h \
		include/editor/minimap.h \
		include/ai/aiautocomplete.h \
		include/ai/aisettingsdialog.h \
		include/tools/visualization/codegraph.h \
		include/tools/visualization/cityscape_widget.h \
		include/audio/audiomonitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/texteditor.o src/app/texteditor.cpp

.build/obj/texteditor_actions.o: src/app/texteditor_actions.cpp src/app/texteditor_private.h \
		include/app/texteditor.h \
		include/editor/codeeditor.h \
		include/editor/syntaxhighlighter.h \
		include/analysis/vulnscanner.h \
		include/analysis/solidityanalyzer.h \
		include/analysis/storageslotvisualizer.h \
		include/story/storyparser.h \
		include/story/storygraph.h \
		include/story/storyplaytest.h \
		include/story/storyexporter.h \
		include/app/breadcrumb_bar.h \
		include/app/command_palette.h \
		include/app/draggable_tabs.h \
		include/app/find_bar.h \
		include/app/search_everywhere.h \
		include/app/terminal_widget.h \
		include/app/todo_panel.h \
		include/app/title_bar.h \
		include/app/welcome_widget.h \
		include/editor/animationwidget.h \
		include/editor/overlays.h \
		include/editor/keyheatmap.h \
		include/editor/vimmode.h \
		include/tools/binary/hexeditor.h \
		include/tools/binary/disassembler.h \
		include/tools/binary/binaryinspector.h \
		include/tools/preview/markdownviewer.h \
		include/editor/minimap.h \
		include/ai/aiautocomplete.h \
		include/ai/aisettingsdialog.h \
		include/tools/visualization/codegraph.h \
		include/tools/visualization/cityscape_widget.h \
		include/audio/audiomonitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/texteditor_actions.o src/app/texteditor_actions.cpp

.build/obj/texteditor_documents.o: src/app/texteditor_documents.cpp src/app/texteditor_private.h \
		include/app/texteditor.h \
		include/editor/codeeditor.h \
		include/editor/syntaxhighlighter.h \
		include/analysis/vulnscanner.h \
		include/analysis/solidityanalyzer.h \
		include/analysis/storageslotvisualizer.h \
		include/story/storyparser.h \
		include/story/storygraph.h \
		include/story/storyplaytest.h \
		include/story/storyexporter.h \
		include/app/breadcrumb_bar.h \
		include/app/command_palette.h \
		include/app/draggable_tabs.h \
		include/app/find_bar.h \
		include/app/search_everywhere.h \
		include/app/terminal_widget.h \
		include/app/todo_panel.h \
		include/app/title_bar.h \
		include/app/welcome_widget.h \
		include/editor/animationwidget.h \
		include/editor/overlays.h \
		include/editor/keyheatmap.h \
		include/editor/vimmode.h \
		include/tools/binary/hexeditor.h \
		include/tools/binary/disassembler.h \
		include/tools/binary/binaryinspector.h \
		include/tools/preview/markdownviewer.h \
		include/editor/minimap.h \
		include/ai/aiautocomplete.h \
		include/ai/aisettingsdialog.h \
		include/tools/visualization/codegraph.h \
		include/tools/visualization/cityscape_widget.h \
		include/audio/audiomonitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/texteditor_documents.o src/app/texteditor_documents.cpp

.build/obj/texteditor_features.o: src/app/texteditor_features.cpp src/app/texteditor_private.h \
		include/app/texteditor.h \
		include/editor/codeeditor.h \
		include/editor/syntaxhighlighter.h \
		include/analysis/vulnscanner.h \
		include/analysis/solidityanalyzer.h \
		include/analysis/storageslotvisualizer.h \
		include/story/storyparser.h \
		include/story/storygraph.h \
		include/story/storyplaytest.h \
		include/story/storyexporter.h \
		include/app/breadcrumb_bar.h \
		include/app/command_palette.h \
		include/app/draggable_tabs.h \
		include/app/find_bar.h \
		include/app/search_everywhere.h \
		include/app/terminal_widget.h \
		include/app/todo_panel.h \
		include/app/title_bar.h \
		include/app/welcome_widget.h \
		include/editor/animationwidget.h \
		include/editor/overlays.h \
		include/editor/keyheatmap.h \
		include/editor/vimmode.h \
		include/tools/binary/hexeditor.h \
		include/tools/binary/disassembler.h \
		include/tools/binary/binaryinspector.h \
		include/tools/preview/markdownviewer.h \
		include/editor/minimap.h \
		include/ai/aiautocomplete.h \
		include/ai/aisettingsdialog.h \
		include/tools/visualization/codegraph.h \
		include/tools/visualization/cityscape_widget.h \
		include/audio/audiomonitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/texteditor_features.o src/app/texteditor_features.cpp

.build/obj/texteditor_panels.o: src/app/texteditor_panels.cpp src/app/texteditor_private.h \
		include/app/texteditor.h \
		include/editor/codeeditor.h \
		include/editor/syntaxhighlighter.h \
		include/analysis/vulnscanner.h \
		include/analysis/solidityanalyzer.h \
		include/analysis/storageslotvisualizer.h \
		include/story/storyparser.h \
		include/story/storygraph.h \
		include/story/storyplaytest.h \
		include/story/storyexporter.h \
		include/app/breadcrumb_bar.h \
		include/app/command_palette.h \
		include/app/draggable_tabs.h \
		include/app/find_bar.h \
		include/app/search_everywhere.h \
		include/app/terminal_widget.h \
		include/app/todo_panel.h \
		include/app/title_bar.h \
		include/app/welcome_widget.h \
		include/editor/animationwidget.h \
		include/editor/overlays.h \
		include/editor/keyheatmap.h \
		include/editor/vimmode.h \
		include/tools/binary/hexeditor.h \
		include/tools/binary/disassembler.h \
		include/tools/binary/binaryinspector.h \
		include/tools/preview/markdownviewer.h \
		include/editor/minimap.h \
		include/ai/aiautocomplete.h \
		include/ai/aisettingsdialog.h \
		include/tools/visualization/codegraph.h \
		include/tools/visualization/cityscape_widget.h \
		include/audio/audiomonitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/texteditor_panels.o src/app/texteditor_panels.cpp

.build/obj/texteditor_tools.o: src/app/texteditor_tools.cpp src/app/texteditor_private.h \
		include/app/texteditor.h \
		include/editor/codeeditor.h \
		include/editor/syntaxhighlighter.h \
		include/analysis/vulnscanner.h \
		include/analysis/solidityanalyzer.h \
		include/analysis/storageslotvisualizer.h \
		include/story/storyparser.h \
		include/story/storygraph.h \
		include/story/storyplaytest.h \
		include/story/storyexporter.h \
		include/app/breadcrumb_bar.h \
		include/app/command_palette.h \
		include/app/draggable_tabs.h \
		include/app/find_bar.h \
		include/app/search_everywhere.h \
		include/app/terminal_widget.h \
		include/app/todo_panel.h \
		include/app/title_bar.h \
		include/app/welcome_widget.h \
		include/editor/animationwidget.h \
		include/editor/overlays.h \
		include/editor/keyheatmap.h \
		include/editor/vimmode.h \
		include/tools/binary/hexeditor.h \
		include/tools/binary/disassembler.h \
		include/tools/binary/binaryinspector.h \
		include/tools/preview/markdownviewer.h \
		include/editor/minimap.h \
		include/ai/aiautocomplete.h \
		include/ai/aisettingsdialog.h \
		include/tools/visualization/codegraph.h \
		include/tools/visualization/cityscape_widget.h \
		include/audio/audiomonitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/texteditor_tools.o src/app/texteditor_tools.cpp

.build/obj/title_bar.o: src/app/title_bar.cpp include/app/title_bar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/title_bar.o src/app/title_bar.cpp

.build/obj/todo_panel.o: src/app/todo_panel.cpp include/app/todo_panel.h \
		include/editor/codeeditor.h \
		include/editor/syntaxhighlighter.h \
		include/analysis/vulnscanner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/todo_panel.o src/app/todo_panel.cpp

.build/obj/welcome_widget.o: src/app/welcome_widget.cpp include/app/welcome_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/welcome_widget.o src/app/welcome_widget.cpp

.build/obj/animationwidget.o: src/editor/animationwidget.cpp include/editor/animationwidget.h \
		include/audio/audiomonitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/animationwidget.o src/editor/animationwidget.cpp

.build/obj/codeeditor.o: src/editor/codeeditor.cpp include/editor/codeeditor.h \
		include/editor/syntaxhighlighter.h \
		include/analysis/vulnscanner.h \
		include/editor/folding_area.h \
		include/editor/line_number_area.h \
		include/editor/minimap.h \
		include/editor/overlays.h \
		include/editor/vimmode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/codeeditor.o src/editor/codeeditor.cpp

.build/obj/keyheatmap.o: src/editor/keyheatmap.cpp include/editor/keyheatmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/keyheatmap.o src/editor/keyheatmap.cpp

.build/obj/linenumberarea.o: src/editor/linenumberarea.cpp include/editor/line_number_area.h \
		include/editor/folding_area.h \
		include/editor/minimap.h \
		include/editor/codeeditor.h \
		include/editor/syntaxhighlighter.h \
		include/analysis/vulnscanner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/linenumberarea.o src/editor/linenumberarea.cpp

.build/obj/overlays.o: src/editor/overlays.cpp include/editor/overlays.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/overlays.o src/editor/overlays.cpp

.build/obj/syntaxhighlighter.o: src/editor/syntaxhighlighter.cpp include/editor/syntaxhighlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/syntaxhighlighter.o src/editor/syntaxhighlighter.cpp

.build/obj/vimmode.o: src/editor/vimmode.cpp include/editor/vimmode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/vimmode.o src/editor/vimmode.cpp

.build/obj/aiautocomplete.o: src/ai/aiautocomplete.cpp include/ai/aiautocomplete.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/aiautocomplete.o src/ai/aiautocomplete.cpp

.build/obj/aisettingsdialog.o: src/ai/aisettingsdialog.cpp include/ai/aisettingsdialog.h \
		include/ai/aiautocomplete.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/aisettingsdialog.o src/ai/aisettingsdialog.cpp

.build/obj/audiomonitor.o: src/audio/audiomonitor.cpp include/audio/audiomonitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/audiomonitor.o src/audio/audiomonitor.cpp

.build/obj/binaryinspector.o: src/tools/binary/binaryinspector.cpp include/tools/binary/binaryinspector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/binaryinspector.o src/tools/binary/binaryinspector.cpp

.build/obj/disassembler.o: src/tools/binary/disassembler.cpp include/tools/binary/disassembler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/disassembler.o src/tools/binary/disassembler.cpp

.build/obj/hexeditor.o: src/tools/binary/hexeditor.cpp include/tools/binary/hexeditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/hexeditor.o src/tools/binary/hexeditor.cpp

.build/obj/markdownviewer.o: src/tools/preview/markdownviewer.cpp include/tools/preview/markdownviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/markdownviewer.o src/tools/preview/markdownviewer.cpp

.build/obj/cityscape_widget.o: src/tools/visualization/cityscape_widget.cpp include/tools/visualization/cityscape_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/cityscape_widget.o src/tools/visualization/cityscape_widget.cpp

.build/obj/codegraph.o: src/tools/visualization/codegraph.cpp include/tools/visualization/codegraph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/codegraph.o src/tools/visualization/codegraph.cpp

.build/obj/solidityanalyzer.o: src/analysis/solidityanalyzer.cpp include/analysis/solidityanalyzer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/solidityanalyzer.o src/analysis/solidityanalyzer.cpp

.build/obj/storageslotvisualizer.o: src/analysis/storageslotvisualizer.cpp include/analysis/storageslotvisualizer.h \
		include/analysis/solidityanalyzer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/storageslotvisualizer.o src/analysis/storageslotvisualizer.cpp

.build/obj/vulnscanner.o: src/analysis/vulnscanner.cpp include/analysis/vulnscanner.h \
		include/editor/syntaxhighlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/vulnscanner.o src/analysis/vulnscanner.cpp

.build/obj/storyexporter.o: src/story/storyexporter.cpp include/story/storyexporter.h \
		include/story/storyparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/storyexporter.o src/story/storyexporter.cpp

.build/obj/storygraph.o: src/story/storygraph.cpp include/story/storygraph.h \
		include/story/storyparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/storygraph.o src/story/storygraph.cpp

.build/obj/storyparser.o: src/story/storyparser.cpp include/story/storyparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/storyparser.o src/story/storyparser.cpp

.build/obj/storyplaytest.o: src/story/storyplaytest.cpp include/story/storyplaytest.h \
		include/story/storyparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/storyplaytest.o src/story/storyplaytest.cpp

.build/obj/moc_texteditor.o: .build/moc/moc_texteditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_texteditor.o .build/moc/moc_texteditor.cpp

.build/obj/moc_breadcrumb_bar.o: .build/moc/moc_breadcrumb_bar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_breadcrumb_bar.o .build/moc/moc_breadcrumb_bar.cpp

.build/obj/moc_command_palette.o: .build/moc/moc_command_palette.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_command_palette.o .build/moc/moc_command_palette.cpp

.build/obj/moc_draggable_tabs.o: .build/moc/moc_draggable_tabs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_draggable_tabs.o .build/moc/moc_draggable_tabs.cpp

.build/obj/moc_find_bar.o: .build/moc/moc_find_bar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_find_bar.o .build/moc/moc_find_bar.cpp

.build/obj/moc_search_everywhere.o: .build/moc/moc_search_everywhere.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_search_everywhere.o .build/moc/moc_search_everywhere.cpp

.build/obj/moc_terminal_widget.o: .build/moc/moc_terminal_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_terminal_widget.o .build/moc/moc_terminal_widget.cpp

.build/obj/moc_todo_panel.o: .build/moc/moc_todo_panel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_todo_panel.o .build/moc/moc_todo_panel.cpp

.build/obj/moc_title_bar.o: .build/moc/moc_title_bar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_title_bar.o .build/moc/moc_title_bar.cpp

.build/obj/moc_welcome_widget.o: .build/moc/moc_welcome_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_welcome_widget.o .build/moc/moc_welcome_widget.cpp

.build/obj/moc_animationwidget.o: .build/moc/moc_animationwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_animationwidget.o .build/moc/moc_animationwidget.cpp

.build/obj/moc_codeeditor.o: .build/moc/moc_codeeditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_codeeditor.o .build/moc/moc_codeeditor.cpp

.build/obj/moc_folding_area.o: .build/moc/moc_folding_area.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_folding_area.o .build/moc/moc_folding_area.cpp

.build/obj/moc_minimap.o: .build/moc/moc_minimap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_minimap.o .build/moc/moc_minimap.cpp

.build/obj/moc_overlays.o: .build/moc/moc_overlays.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_overlays.o .build/moc/moc_overlays.cpp

.build/obj/moc_keyheatmap.o: .build/moc/moc_keyheatmap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_keyheatmap.o .build/moc/moc_keyheatmap.cpp

.build/obj/moc_syntaxhighlighter.o: .build/moc/moc_syntaxhighlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_syntaxhighlighter.o .build/moc/moc_syntaxhighlighter.cpp

.build/obj/moc_vimmode.o: .build/moc/moc_vimmode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_vimmode.o .build/moc/moc_vimmode.cpp

.build/obj/moc_aiautocomplete.o: .build/moc/moc_aiautocomplete.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_aiautocomplete.o .build/moc/moc_aiautocomplete.cpp

.build/obj/moc_aisettingsdialog.o: .build/moc/moc_aisettingsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_aisettingsdialog.o .build/moc/moc_aisettingsdialog.cpp

.build/obj/moc_audiomonitor.o: .build/moc/moc_audiomonitor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_audiomonitor.o .build/moc/moc_audiomonitor.cpp

.build/obj/moc_binaryinspector.o: .build/moc/moc_binaryinspector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_binaryinspector.o .build/moc/moc_binaryinspector.cpp

.build/obj/moc_disassembler.o: .build/moc/moc_disassembler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_disassembler.o .build/moc/moc_disassembler.cpp

.build/obj/moc_hexeditor.o: .build/moc/moc_hexeditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_hexeditor.o .build/moc/moc_hexeditor.cpp

.build/obj/moc_markdownviewer.o: .build/moc/moc_markdownviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_markdownviewer.o .build/moc/moc_markdownviewer.cpp

.build/obj/moc_cityscape_widget.o: .build/moc/moc_cityscape_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_cityscape_widget.o .build/moc/moc_cityscape_widget.cpp

.build/obj/moc_codegraph.o: .build/moc/moc_codegraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_codegraph.o .build/moc/moc_codegraph.cpp

.build/obj/moc_storageslotvisualizer.o: .build/moc/moc_storageslotvisualizer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_storageslotvisualizer.o .build/moc/moc_storageslotvisualizer.cpp

.build/obj/moc_vulnscanner.o: .build/moc/moc_vulnscanner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_vulnscanner.o .build/moc/moc_vulnscanner.cpp

.build/obj/moc_storygraph.o: .build/moc/moc_storygraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_storygraph.o .build/moc/moc_storygraph.cpp

.build/obj/moc_storyplaytest.o: .build/moc/moc_storyplaytest.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/obj/moc_storyplaytest.o .build/moc/moc_storyplaytest.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

