#ifndef JIM_TEXTEDITOR_PRIVATE_H
#define JIM_TEXTEDITOR_PRIVATE_H

#include "texteditor.h"
#include "breadcrumb_bar.h"
#include "command_palette.h"
#include "draggable_tabs.h"
#include "find_bar.h"
#include "search_everywhere.h"
#include "terminal_widget.h"
#include "todo_panel.h"
#include "title_bar.h"
#include "welcome_widget.h"
#include "animationwidget.h"
#include "codeeditor.h"
#include "overlays.h"
#include "syntaxhighlighter.h"
#include "keyheatmap.h"
#include "vimmode.h"
#include "hexeditor.h"
#include "disassembler.h"
#include "binaryinspector.h"
#include "markdownviewer.h"
#include "minimap.h"
#include "aiautocomplete.h"
#include "aisettingsdialog.h"
#include "codegraph.h"
#include "solidityanalyzer.h"
#include "storageslotvisualizer.h"
#include "cityscape_widget.h"
#include "audiomonitor.h"

#include <QApplication>
#include <QCloseEvent>
#include <QColorDialog>
#include <QComboBox>
#include <QDateTime>
#include <QDesktopServices>
#include <QDialog>
#include <QDialogButtonBox>
#include <QDir>
#include <QDockWidget>
#include <QDrag>
#include <QEasingCurve>
#include <QFileDialog>
#include <QFileInfo>
#include <QFileSystemModel>
#include <QFileSystemWatcher>
#include <QFontDatabase>
#include <QFontDialog>
#include <QFrame>
#include <QGraphicsDropShadowEffect>
#include <QGraphicsOpacityEffect>
#include <QGridLayout>
#include <QGuiApplication>
#include <QHeaderView>
#include <QHBoxLayout>
#include <QInputDialog>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QListWidget>
#include <QListWidgetItem>
#include <QMenuBar>
#include <QMessageBox>
#include <QMimeData>
#include <QNetworkRequest>
#include <QPainter>
#include <QPainterPath>
#include <QProcess>
#include <QProcessEnvironment>
#include <QPropertyAnimation>
#include <QPushButton>
#include <QRandomGenerator>
#include <QRadialGradient>
#include <QRegularExpression>
#include <QSaveFile>
#include <QScrollBar>
#include <QSettings>
#include <QSoundEffect>
#include <QSplitter>
#include <QStackedWidget>
#include <QStandardPaths>
#include <QStatusBar>
#include <QTabBar>
#include <QTableWidget>
#include <QTextBlock>
#include <QTextStream>
#include <QTimer>
#include <QToolBar>
#include <QTreeView>
#include <QVariantAnimation>
#include <QVBoxLayout>
#include <QWheelEvent>

#include <algorithm>
#include <cmath>
#include <functional>

#endif
